//! AXS15231B QSPI 320×480 display driver (JC3248W535C "Touch 3.5\"" panel).
//!
//! Port of [`H01001000/esp-axs15231b-display`](https://github.com/H01001000/esp-axs15231b-display)
//! (`src/axs15231b.rs`) from **esp-hal 1.x + the custom `spi-half-duplex-async-v1`
//! branch** to the workspace's pinned **esp-hal 0.23.1**. The full init sequence
//! and the command/data QSPI protocol are ported 1:1.
//!
//! # Protocol (AXS15231B)
//!
//! The controller is driven over QSPI in half-duplex mode, one transaction per
//! register access, with CS asserted for the whole transaction:
//!
//! * **command phase** (8-bit, SIO0): opcode `0x02` = write command, `0x32` =
//!   write color (pixel data), `0x0B` = read.
//! * **address phase** (24-bit, SIO0): `register << 8` (register number in the
//!   middle byte, low byte zero).
//! * **data phase**: 1-bit (Single) for register payloads, **4-bit (Quad) on
//!   D0..D3** for pixel data. This is why the SPI bus must be QSPI-capable
//!   (SPI2 on the ESP32-S3, pins SCK/CS + SIO0..SIO3).
//!
//! There is no DC line: command vs data is encoded by the opcode + address
//! phase, not by a GPIO (the "DC" pin is not used at all on this controller).
//!
//! # esp-hal 0.23.1 vs 1.x — API differences resolved in this port
//!
//! | 1.x (reference driver)                            | 0.23.1 (this port)                                 |
//! |---------------------------------------------------|----------------------------------------------------|
//! | `SpiDmaBus<'d, Async>::half_duplex_write().await` (custom branch, async) | `SpiDmaBus<'d, Blocking>::half_duplex_write()` — DMA, **blocking**; esp-hal 0.23.1 has no async half-duplex API |
//! | `with_sio0(sio0)`                                 | `with_mosi(sio0)` — SIO0 output is wired through MOSI; `with_sio0` does not exist in 0.23.1 |
//! | pins: `impl PeripheralOutput<'a> + PeripheralInput<'a>` | pins: `impl Peripheral<P: PeripheralOutput> + 'd` (peripheral-mapping API) |
//! | `esp_hal::spi::master::DataMode`                  | `esp_hal::spi::DataMode` (moved one level up)      |
//! | `esp_hal::time::Rate::from_mhz(60)`               | `esp_hal::time::RateExtU32`: `60u32.MHz()` (`Rate` is no longer re-exported by `esp_hal::time`) |
//! | `with_frequency`/`with_mode` builder (esp-hal 1.x derive) | same builder names — generated by `#[derive(procmacros::BuilderLite)]` in 0.23.1, consuming `self` |
//! | `esp_alloc::ExternalMemory` framebuffer           | framebuffer passed in as `&[u16]` / `&mut [u16]` — allocation strategy (PSRAM via `esp_alloc`, static, …) is left to the caller |
//!
//! Unchanged between the two versions: `Command::_8Bit(u16, DataMode)`,
//! `Address::_24Bit(u32, DataMode)`, `DataMode::{Single,Quad}`, `Mode::_3`,
//! `dma_buffers!`, `DmaRxBuf::new`/`DmaTxBuf::new`, `with_sck/with_sio1..3/with_cs/with_dma/with_buffers`.
//!
//! # Async note
//!
//! The reference driver awaits each half-duplex DMA transfer (async branch of
//! esp-hal 1.x). esp-hal 0.23.1 only offers `half_duplex_write` as a blocking
//! (busy-wait on transfer completion) DMA call, so this port's methods are
//! plain `fn`s. Run the driver in a dedicated embassy task (the transfers are
//! DMA-backed and short: ~2 ms for a full 320×480×RGB565 flush at 60 MHz quad).
//!
//! Plan B if a future esp-hal upgrade removes/changes the blocking half-duplex
//! API: keep 8-bit SPI for the command/address phases and bit-bang the data
//! phase on D0..D3 with GPIO — ~2× slower, same protocol framing.

use esp_hal::{
    dma::{DmaChannelFor, DmaRxBuf, DmaTxBuf},
    gpio::interconnect::{PeripheralInput, PeripheralOutput},
    gpio::{Level, Output},
    peripheral::Peripheral,
    spi::{
        master::{Address, Command, Config, Instance, Spi, SpiDmaBus},
        AnySpi, DataMode, Mode,
    },
    time::RateExtU32,
    Blocking,
};

/// SPI opcode: write command / register data (8-bit, SIO0).
pub const LCD_OPCODE_WRITE_CMD: u16 = 0x02;
/// SPI opcode: read (8-bit, SIO0).
pub const LCD_OPCODE_READ_CMD: u16 = 0x0B;
/// SPI opcode: write pixel color data (QSPI data phase, D0..D3).
pub const LCD_OPCODE_WRITE_COLOR: u16 = 0x32;

/// Panel width in pixels.
pub const LCD_WIDTH: u16 = 320;
/// Panel height in pixels.
pub const LCD_HEIGHT: u16 = 480;
/// Number of RGB565 pixels in a full frame.
pub const BOX_SIZE: usize = LCD_HEIGHT as usize * LCD_WIDTH as usize;

/// Number of pixel lines pushed per QSPI burst during a flush.
const FLUSH_LINES: usize = 48;
/// Command used for the first pixel burst of a flush (frame start).
const RAMWR: u32 = 0x2C;
/// Command used for continuation pixel bursts (no frame reset).
const RAMWRC: u32 = 0x3C;

/// Payload `0xA0` de la table **Espressif** (`esp_lcd_axs15231b.c`) :
/// octet 0 = `0x00` → `cr_format_cmd3a_en`, octet 6 = `0x64`. Le format pixel
/// est alors fixé par COLMOD (`0x3A`) envoyé **après**.
#[rustfmt::skip]
const A0_ESPRESSIF: &[u8] = &[
    0x00, 0x10, 0x00, 0x02, 0x00, 0x00, 0x64, 0x3F, 0x20,
    0x05, 0x3F, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Payload `0xA0` de la table **vendor / Arduino_GFX** : octet 0 = `0xC0`,
/// octet 6 = `0x04`. Le format pixel est porté par `0xA0` lui-même et COLMOD
/// n'est pas envoyé.
///
/// ⚠️ Ces deux octets sont à re-vérifier contre
/// `Arduino_AXS15231B.h` (table `axs15231b_init_operations`, entrée `0xA0`) :
/// ce sont EUX qui décident du mode couleur vs gris. Les 15 autres octets sont
/// communs aux deux tables.
#[rustfmt::skip]
const A0_VENDOR: &[u8] = &[
    0xC0, 0x10, 0x00, 0x02, 0x00, 0x00, 0x04, 0x3F, 0x20,
    0x05, 0x3F, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Façon dont le format pixel (RGB565 vs gris) est programmé pendant l'init.
///
/// Le panneau reste en niveaux de gris tant que `cr_qspis_datamode` (registre
/// vendor `0xA0`) n'est pas correct. Les trois variantes couvrent les
/// combinaisons plausibles ; flasher les trois lève le doute en quelques
/// minutes. Voir [`Axs15231b::init_with`].
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum PixelFormat {
    /// Table vendor/Arduino : `0xA0` = [`A0_VENDOR`], **pas** de COLMOD.
    /// C'est la configuration qui est prouvée en couleurs sur cette carte
    /// (BlockClock / Arduino_GFX) — donc le défaut.
    VendorA0Only,
    /// Table Espressif : `0xA0` = [`A0_ESPRESSIF`] puis COLMOD `0x3A = 0x55`.
    Cmd3aAfterA0,
    /// Ceinture et bretelles : `0xA0` vendor **et** COLMOD après.
    VendorA0PlusCmd3a,
}

impl Default for PixelFormat {
    fn default() -> Self {
        Self::VendorA0Only
    }
}

impl PixelFormat {
    fn a0_payload(self) -> &'static [u8] {
        match self {
            Self::Cmd3aAfterA0 => A0_ESPRESSIF,
            Self::VendorA0Only | Self::VendorA0PlusCmd3a => A0_VENDOR,
        }
    }

    /// Valeur COLMOD à envoyer juste après `0xA0`, ou `None`.
    fn colmod(self) -> Option<u8> {
        match self {
            Self::VendorA0Only => None,
            // 0x55 = RGB565.
            Self::Cmd3aAfterA0 | Self::VendorA0PlusCmd3a => Some(0x55),
        }
    }
}

/// AXS15231B display controller over QSPI (SPI2 half-duplex DMA).
///
/// Owns the SPI bus + DMA buffers. `flush()` expects the frame buffer as a
/// `&[u16]` (RGB565, length ≥ [`BOX_SIZE`]) so the caller keeps full control
/// over where it lives (PSRAM via `esp_alloc`, `static`, …).
pub struct Axs15231b<'d> {
    spi: SpiDmaBus<'d, Blocking>,
    /// CS piloté en GPIO MANUEL — comme le bus Arduino_ESP32QSPI : CS_LOW une
    /// fois, tous les chunks, CS_HIGH à la fin (le pointeur d'écriture continue).
    cs: Output<'d>,
}

impl<'d> Axs15231b<'d> {
    /// Creates the driver and takes ownership of the given pins, SPI
    /// peripheral and DMA channel.
    ///
    /// Pin mapping for the JC3248W535C (also in `lightningpos_hal::pins::display`):
    /// SCK=47, SIO0/D0=21, SIO1/D1=48, SIO2/D2=40, SIO3/D3=39, CS=45,
    /// SPI2, DMA channel 0, backlight GPIO 1.
    #[allow(clippy::too_many_arguments)]
    pub fn new<SCK, SIO0, SIO1, SIO2, SIO3, CS, CH, I>(
        sck: impl Peripheral<P = SCK> + 'd,
        sio0: impl Peripheral<P = SIO0> + 'd,
        sio1: impl Peripheral<P = SIO1> + 'd,
        sio2: impl Peripheral<P = SIO2> + 'd,
        sio3: impl Peripheral<P = SIO3> + 'd,
        cs: impl Peripheral<P = CS> + 'd,
        dma_channel: impl Peripheral<P = CH> + 'd,
        spi: impl Peripheral<P = I> + 'd,
    ) -> Self
    where
        SCK: PeripheralOutput,
        SIO0: PeripheralInput + PeripheralOutput,
        SIO1: PeripheralOutput,
        SIO2: PeripheralOutput,
        SIO3: PeripheralOutput,
        CS: esp_hal::gpio::OutputPin,
        CH: DmaChannelFor<AnySpi>,
        I: Instance,
    {
        // TX buffer : 30 720 o = 48 lignes (LIMITE MATÉRIELLE : le registre
        // SPI_MS_DLEN plafonne une transaction à ~32 Ko de données — on ne peut
        // pas faire plus gros en un seul transfert).
        let (rx_buffer, rx_descriptors, tx_buffer, tx_descriptors) =
            esp_hal::dma_buffers!(4096, 4096 * 8);
        let dma_rx_buf = DmaRxBuf::new(rx_descriptors, rx_buffer).unwrap();
        let dma_tx_buf = DmaTxBuf::new(tx_descriptors, tx_buffer).unwrap();

        let spi = Spi::new(
            spi,
            Config::default()
                // 40 MHz : les pins (47/21/48/40/39/45) ne sont PAS les pins
                // IOMUX de SPI2 sur l'ESP32-S3 (FSPI IOMUX = GPIO 9..14), donc
                // tout passe par la GPIO matrix, garantie jusqu'à 40 MHz
                // seulement. Et 100 MHz est de toute façon inatteignable : la
                // source d'horloge du GPSPI plafonne à 80 MHz.
                .with_frequency(80u32.MHz())
                // Mode 0 = SPI_MODE0 du BlockClock (Arduino_ESP32QSPI), prouvé
                // avec couleurs sur cette carte. Le Mode 3 donne du gris.
                .with_mode(Mode::_0),
        )
        .unwrap()
        .with_sck(sck)
        // 0.23.1 has no `with_sio0`: MOSI *is* SIO0 in half-duplex mode.
        .with_mosi(sio0)
        .with_sio1(sio1)
        .with_sio2(sio2)
        .with_sio3(sio3)
        // PAS de CS matériel : piloté en GPIO manuel (continuité CS requise pour
        // le stream pixel, comme Arduino_ESP32QSPI).
        .with_dma(dma_channel)
        .with_buffers(dma_rx_buf, dma_tx_buf);

        let cs = Output::new(cs, Level::High);

        Self { spi, cs }
    }

    /// Petit transfert half-duplex (variante blocking SpiDmaBus, buffer interne).
    fn write_small(
        &mut self,
        data_mode: DataMode,
        cmd: Command,
        address: Address,
        data: &[u8],
    ) {
        self.spi
            .half_duplex_write(data_mode, cmd, address, 0, data)
            .unwrap();
    }

    /// Sends a register command with its payload over the 1-bit data phase.
    ///
    /// Transaction: opcode `0x02` + adresse `cmd << 8` + données, TOUT en
    /// SINGLE (1-bit). La datasheet AXS15231B §4.4.1 : « CMD_WR only use SDA ».
    /// Les flags MULTILINE_CMD|ADDR de l'Arduino ESP32QSPI sont des no-ops
    /// (data_lines=1 → cmd/addr restent 1-line, cf. spi_master.c v4.4). Seule
    /// la phase DATA pixel (0x32) passe en 4-line.
    pub fn send_cmd(&mut self, cmd: u32, data: &[u8]) {
        self.cs.set_low();
        // CMD_WR = tout en SINGLE (datasheet §4.4.1 « only use SDA »).
        // L'Arduino (writeC8Bytes) : MULTILINE_CMD|ADDR, mais data_lines=1
        // (pas de flag QIO) → cmd/addr_lines = data_lines = 1 = SINGLE aussi.
        self.write_small(
            DataMode::Single,
            Command::_8Bit(LCD_OPCODE_WRITE_CMD, DataMode::Single),
            Address::_24Bit(cmd << 8, DataMode::Single),
            data,
        );
        self.cs.set_high();
    }

    /// Lit un registre du panneau (opcode 0x0B, cf. datasheet §4.4.2 CMD_RD).
    /// Utilisé pour le diagnostic (RDID1=0xDA doit renvoyer 0x40).
    ///
    /// La phase données est en SINGLE : `0x0B` est le Fast Read 1-line, le
    /// panneau ne pilote que SDA en réponse (la sortie quad serait `0x6B`).
    /// Lire en Quad ici renvoie du bruit — c'est ce qui rendait la relecture
    /// de 0xA0 ininterprétable.
    pub fn read_cmd(&mut self, cmd: u32, buf: &mut [u8]) {
        self.cs.set_low();
        self.spi
            .half_duplex_read(
                DataMode::Single,
                Command::_8Bit(0x0B, DataMode::Single),
                Address::_24Bit(cmd << 8, DataMode::Single),
                8,
                buf,
            )
            .unwrap();
        self.cs.set_high();
    }

    /// Sends pixel data to a color-write register over the 4-bit QSPI data
    /// phase (D0..D3).
    ///
    /// Transaction: opcode `0x32`, 24-bit address `cmd << 8`, then `data`
    /// in Quad (4-bit) mode.
    pub fn send_color(&mut self, cmd: u32, data: &[u8]) {
        self.write_small(
            DataMode::Quad,
            Command::_8Bit(LCD_OPCODE_WRITE_COLOR, DataMode::Single),
            Address::_24Bit(cmd << 8, DataMode::Single),
            data,
        );
    }

    /// Runs the complete controller init sequence with the default pixel-format
    /// variant. Voir [`Axs15231b::init_with`] pour bissecter le bug « tout gris ».
    pub fn init(&mut self) {
        self.init_with(PixelFormat::default());
    }

    /// Init complète, avec choix explicite de la façon dont le format pixel est
    /// programmé.
    ///
    /// # Pourquoi ce paramètre existe
    ///
    /// Le champ `cr_qspis_datamode` (RGB565 vs **gray**) vit dans le registre
    /// vendor `0xA0`, qui est **re-latché à chaque écriture de 0xA0**. Deux
    /// tables incompatibles circulent pour ce panneau :
    ///
    /// * Espressif (`esp_lcd_axs15231b.c`) : `0xA0[0]=0x00` active
    ///   `cr_format_cmd3a_en`, et c'est **COLMOD (`0x3A`) envoyé APRÈS `0xA0`**
    ///   qui fixe le format.
    /// * vendor / Arduino_GFX : `0xA0` porte lui-même le format, et `0x3A`
    ///   n'est **jamais** envoyé.
    ///
    /// L'ancienne version de ce driver mélangeait les deux : payload Espressif
    /// (`0x00`/`0x64`) **plus** un `0x3A` envoyé *avant* `0xA0` — donc écrasé —
    /// et même avant le déverrouillage `0xBB {…,0x5A,0xA5}`. Résultat : le
    /// panneau restait sur son datamode par défaut = niveaux de gris.
    pub fn init_with(&mut self, format: PixelFormat) {
        // SWRESET (0x01) + 200 ms AVANT la table — le BlockClock (tftInit) le
        // fait systématiquement (il n'a pas de RST hardware : GFX_NOT_DEFINED).
        // Sans reset, le panneau garde l'état résiduel du boot chaud et les
        // commandes custom (0xA0 → cr_qspis_datamode) ne prennent pas effet.
        self.send_cmd(0x01, &[]);
        embassy_time::block_for(embassy_time::Duration::from_millis(200));

        let _ = format;
        // Table v1.4.9 (BlockClock) — 0xA0 = 0xC0.
        #[rustfmt::skip]
        const AXS15231B_INIT_CMDS: &[(u32, &[u8], u32)] = &[
            (0xBB, &[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5A, 0xA5], 0),
            (0xA0, &[0xC0, 0x10, 0x00, 0x02, 0x00, 0x00, 0x04, 0x3F, 0x20, 0x05, 0x3F, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00], 0),
            (0xA2, &[0x30, 0x3C, 0x24, 0x14, 0xD0, 0x20, 0xFF, 0xE0, 0x40, 0x19, 0x80, 0x80, 0x80, 0x20, 0xf9, 0x10, 0x02, 0xff, 0xff, 0xF0, 0x90, 0x01, 0x32, 0xA0, 0x91, 0xE0, 0x20, 0x7F, 0xFF, 0x00, 0x5A], 0),
            (0xD0, &[0xE0, 0x40, 0x51, 0x24, 0x08, 0x05, 0x10, 0x01, 0x20, 0x15, 0xC2, 0x42, 0x22, 0x22, 0xAA, 0x03, 0x10, 0x12, 0x60, 0x14, 0x1E, 0x51, 0x15, 0x00, 0x8A, 0x20, 0x00, 0x03, 0x3A, 0x12], 0),
            (0xA3, &[0xA0, 0x06, 0xAA, 0x00, 0x08, 0x02, 0x0A, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x00, 0x55, 0x55], 0),
            (0xC1, &[0x31, 0x04, 0x02, 0x02, 0x71, 0x05, 0x24, 0x55, 0x02, 0x00, 0x41, 0x00, 0x53, 0xFF, 0xFF, 0xFF, 0x4F, 0x52, 0x00, 0x4F, 0x52, 0x00, 0x45, 0x3B, 0x0B, 0x02, 0x0d, 0x00, 0xFF, 0x40], 0),
            (0xC3, &[0x00, 0x00, 0x00, 0x50, 0x03, 0x00, 0x00, 0x00, 0x01, 0x80, 0x01], 0),
            (0xC4, &[0x00, 0x24, 0x33, 0x80, 0x00, 0xea, 0x64, 0x32, 0xC8, 0x64, 0xC8, 0x32, 0x90, 0x90, 0x11, 0x06, 0xDC, 0xFA, 0x00, 0x00, 0x80, 0xFE, 0x10, 0x10, 0x00, 0x0A, 0x0A, 0x44, 0x50], 0),
            (0xC5, &[0x18, 0x00, 0x00, 0x03, 0xFE, 0x3A, 0x4A, 0x20, 0x30, 0x10, 0x88, 0xDE, 0x0D, 0x08, 0x0F, 0x0F, 0x01, 0x3A, 0x4A, 0x20, 0x10, 0x10, 0x00], 0),
            (0xC6, &[0x05, 0x0A, 0x05, 0x0A, 0x00, 0xE0, 0x2E, 0x0B, 0x12, 0x22, 0x12, 0x22, 0x01, 0x03, 0x00, 0x3F, 0x6A, 0x18, 0xC8, 0x22], 0),
            (0xC7, &[0x50, 0x32, 0x28, 0x00, 0xa2, 0x80, 0x8f, 0x00, 0x80, 0xff, 0x07, 0x11, 0x9c, 0x67, 0xff, 0x24, 0x0c, 0x0d, 0x0e, 0x0f], 0),
            (0xC9, &[0x33, 0x44, 0x44, 0x01], 0),
            (0xCF, &[0x2C, 0x1E, 0x88, 0x58, 0x13, 0x18, 0x56, 0x18, 0x1E, 0x68, 0x88, 0x00, 0x65, 0x09, 0x22, 0xC4, 0x0C, 0x77, 0x22, 0x44, 0xAA, 0x55, 0x08, 0x08, 0x12, 0xA0, 0x08], 0),
            (0xD5, &[0x40, 0x8E, 0x8D, 0x01, 0x35, 0x04, 0x92, 0x74, 0x04, 0x92, 0x74, 0x04, 0x08, 0x6A, 0x04, 0x46, 0x03, 0x03, 0x03, 0x03, 0x82, 0x01, 0x03, 0x00, 0xE0, 0x51, 0xA1, 0x00, 0x00, 0x00], 0),
            (0xD6, &[0x10, 0x32, 0x54, 0x76, 0x98, 0xBA, 0xDC, 0xFE, 0x93, 0x00, 0x01, 0x83, 0x07, 0x07, 0x00, 0x07, 0x07, 0x00, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00, 0x84, 0x00, 0x20, 0x01, 0x00], 0),
            (0xD7, &[0x03, 0x01, 0x0b, 0x09, 0x0f, 0x0d, 0x1E, 0x1F, 0x18, 0x1d, 0x1f, 0x19, 0x40, 0x8E, 0x04, 0x00, 0x20, 0xA0, 0x1F], 0),
            (0xD8, &[0x02, 0x00, 0x0a, 0x08, 0x0e, 0x0c, 0x1E, 0x1F, 0x18, 0x1d, 0x1f, 0x19], 0),
            (0xD9, &[0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F], 0),
            (0xDD, &[0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F, 0x1F], 0),
            (0xDF, &[0x44, 0x73, 0x4B, 0x69, 0x00, 0x0A, 0x02, 0x90], 0),
            (0xE0, &[0x3B, 0x28, 0x10, 0x16, 0x0c, 0x06, 0x11, 0x28, 0x5c, 0x21, 0x0D, 0x35, 0x13, 0x2C, 0x33, 0x28, 0x0D], 0),
            (0xE1, &[0x37, 0x28, 0x10, 0x16, 0x0b, 0x06, 0x11, 0x28, 0x5C, 0x21, 0x0D, 0x35, 0x14, 0x2C, 0x33, 0x28, 0x0F], 0),
            (0xE2, &[0x3B, 0x07, 0x12, 0x18, 0x0E, 0x0D, 0x17, 0x35, 0x44, 0x32, 0x0C, 0x14, 0x14, 0x36, 0x3A, 0x2F, 0x0D], 0),
            (0xE3, &[0x37, 0x07, 0x12, 0x18, 0x0E, 0x0D, 0x17, 0x35, 0x44, 0x32, 0x0C, 0x14, 0x14, 0x36, 0x32, 0x2F, 0x0F], 0),
            (0xE4, &[0x3B, 0x07, 0x12, 0x18, 0x0E, 0x0D, 0x17, 0x39, 0x44, 0x2E, 0x0C, 0x14, 0x14, 0x36, 0x3A, 0x2F, 0x0D], 0),
            (0xE5, &[0x37, 0x07, 0x12, 0x18, 0x0E, 0x0D, 0x17, 0x39, 0x44, 0x2E, 0x0C, 0x14, 0x14, 0x36, 0x3A, 0x2F, 0x0F], 0),
            (0xA4, &[0x85, 0x85, 0x95, 0x82, 0xAF, 0xAA, 0xAA, 0x80, 0x10, 0x30, 0x40, 0x40, 0x20, 0xFF, 0x60, 0x30], 0),
            (0xA4, &[0x85, 0x85, 0x95, 0x85], 0),
            (0xBB, &[0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], 0),
            (0x11, &[0x00], 120),
            (0x29, &[0x00], 100),
            (0x2C, &[0x00, 0x00, 0x00, 0x00], 0),
        ];

        for &(cmd, data, delay_ms) in AXS15231B_INIT_CMDS {
            self.send_cmd(cmd, data);
            if delay_ms > 0 {
                embassy_time::block_for(embassy_time::Duration::from_millis(delay_ms as u64));
            }
        }

        self.send_cmd(0x20, &[]);
        self.send_cmd(0x36, &[0x00]);
    }

    /// Sets the display window for the next pixel write(s).
    fn set_address_window(&mut self, sx: u16, sy: u16, ex: u16, ey: u16) {
        // Comme writeAddrWindow d'Arduino_GFX : writeC8D16D16(CASET, ...) puis
        // writeC8D16D16(RASET, ...) — chaque commande = sa période CS.
        self.send_cmd(
            0x2a,
            &[
                (sx >> 8) as u8,
                (sx & 0xff) as u8,
                (ex >> 8) as u8,
                (ex & 0xff) as u8,
            ],
        );
        self.send_cmd(
            0x2b,
            &[
                (sy >> 8) as u8,
                (sy & 0xff) as u8,
                (ey >> 8) as u8,
                (ey & 0xff) as u8,
            ],
        );
    }

    /// Ouvre une frame plein écran : fenêtre (0,0,319,479) + commande RAMWR
    /// seule. Les données suivent par appels successifs à [`flush_chunk`]
    /// (RAMWRC) — le pointeur d'écriture continue. C'est le seul mode fiable
    /// sur ce panneau : il IGNORE les fenêtres d'adressage partielles
    /// (leçon BlockClock / me-processware : « REQUIRED for QSPI! »).
    pub fn start_frame(&mut self) {
        self.set_address_window(0, 0, LCD_WIDTH - 1, LCD_HEIGHT - 1);
        self.send_cmd(RAMWR, &[]);
    }

    /// Envoie une bande de `height` lignes (multiple de [`FLUSH_LINES`]) dans
    /// la frame ouverte par [`start_frame`]. `data` contient `320*height`
    /// pixels RGB565, lignes dans l'ordre.
    pub fn flush_chunk(&mut self, height: u16, data: &[u16]) {
        assert!(data.len() >= 320 * height as usize, "chunk too small");

        for start in (0..height as usize).step_by(FLUSH_LINES) {
            let end = (start + FLUSH_LINES).min(height as usize);
            // SAFETY: a `[u16]` slice of sufficient length is a contiguous byte
            // range of twice that length.
            let bytes: &[u8] = unsafe {
                core::slice::from_raw_parts(
                    data[start * 320..end * 320].as_ptr() as *const u8,
                    (end - start) * 320 * 2,
                )
            };

            self.send_color(RAMWRC, bytes);
        }
    }

    /// Flush pleine frame — EXACTEMENT comme le bus Arduino_ESP32QSPI (BlockClock) :
    /// fenêtre + RAMWR (chacun leur CS), PUIS le stream pixel en UNE période CS
    /// bas : premier chunk cmd 0x32 + addr 0x3C00, chunks suivants données pures
    /// (le pointeur d'écriture continue), CS haut à la fin.
    pub fn flush_full(&mut self, framebuffer: &[u16]) {
        assert!(framebuffer.len() >= BOX_SIZE);

        self.set_address_window(0, 0, LCD_WIDTH - 1, LCD_HEIGHT - 1);

        // Séquence EXACTE de la référence H01001000/esp-axs15231b-display qui
        // MARCHE sur cette carte : par bandes de 48 lignes, on ré-émet cmd+addr
        // à chaque bande (0x2C pour la 1re, 0x3C pour les suivantes). PAS de
        // "données pures" en continuation — c'est cette continuation sans
        // cmd/addr qui est suspecte.
        const LINE_TO_SEND: usize = 48;
        for y in (0..LCD_HEIGHT as usize).step_by(LINE_TO_SEND) {
            let start = y * LCD_WIDTH as usize;
            let end = (y + LINE_TO_SEND) * LCD_WIDTH as usize;
            // SAFETY: contiguous sub-slice of the framebuffer.
            let bytes: &[u8] = unsafe {
                core::slice::from_raw_parts(
                    framebuffer[start..end].as_ptr() as *const u8,
                    (end - start) * 2,
                )
            };
            if y == 0 {
                self.send_color(RAMWR, bytes);
            } else {
                self.send_color(RAMWRC, bytes);
            }
        }
    }

    /// Flush a horizontal strip of the screen (PSRAM-less mode).
    ///
    /// Writes `width*height` RGB565 words starting at (x, y). Useful on boards
    /// without PSRAM: render the 320×480 screen as N strips of ≤48 lines with
    /// a small internal buffer. `data.len()` must be ≥ `width*height`.
    pub fn flush_window(&mut self, x: u16, y: u16, width: u16, height: u16, data: &[u16]) {
        assert!(
            data.len() >= width as usize * height as usize,
            "strip buffer too small"
        );
        assert!(x + width <= LCD_WIDTH && y + height <= LCD_HEIGHT, "window out of bounds");

        self.set_address_window(x, y, x + width - 1, y + height - 1);

        // Séquence EXACTE du bus Arduino_ESP32QSPI (prouvé sur cette carte par
        // le projet BlockClock) : commande RAMWR (0x2C) envoyée SEULE via
        // l'opcode commande, puis TOUTES les données pixel via l'opcode couleur
        // avec l'adresse 0x3C00 (RAMWRC) — jamais 0x2C00 en phase données.
        self.send_cmd(RAMWR, &[]);

        for start in (0..height as usize).step_by(FLUSH_LINES) {
            let end = (start + FLUSH_LINES).min(height as usize);
            // SAFETY: a `[u16]` slice of sufficient length is a contiguous byte
            // range of twice that length.
            let bytes: &[u8] = unsafe {
                core::slice::from_raw_parts(
                    data[start * width as usize..end * width as usize].as_ptr() as *const u8,
                    (end - start) * width as usize * 2,
                )
            };

            self.send_color(RAMWRC, bytes);
        }
    }

    /// Flushes a full RGB565 frame buffer to the panel.
    ///
    /// `framebuffer` must contain at least [`BOX_SIZE`] (`320*480`) little-
    /// endian RGB565 words — matching the in-memory layout of `[u16]` on the
    /// Xtensa (native endianness). Pixel data is pushed in [`FLUSH_LINES`]
    /// bursts of QSPI writes: `0x2C` for the first burst, `0x3C` (RAM write
    /// continue) for the following ones.
    pub fn flush(&mut self, framebuffer: &[u16]) {
        assert!(framebuffer.len() >= BOX_SIZE, "framebuffer too small");

        self.set_address_window(0, 0, LCD_WIDTH - 1, LCD_HEIGHT - 1);
        self.send_cmd(RAMWR, &[]);

        for start in (0..LCD_HEIGHT as usize).step_by(FLUSH_LINES) {
            let end = start + FLUSH_LINES;
            // SAFETY: a `[u16]` slice of length >= BOX_SIZE is a contiguous
            // byte range of twice that length; reinterpreting it as `[u8]`
            // keeps the same memory and never exceeds the slice bounds.
            let data: &[u8] = unsafe {
                core::slice::from_raw_parts(
                    framebuffer[start..end].as_ptr() as *const u8,
                    (end - start) * 2,
                )
            };

            self.send_color(RAMWRC, data);
        }
    }
}

/// CPU-side RGB565 frame buffer (320×480) with basic drawing primitives.
///
/// The driver itself is buffer-agnostic (see [`Axs15231b::flush`]); this type
/// is a convenience render target. To draw with `embedded-graphics`, implement
/// `DrawTarget` on a wrapper of [`FrameBuffer::as_mut_slice`] (not included
/// here to keep `lightningpos-display` free of that dependency).
pub struct FrameBuffer<'a> {
    data: &'a mut [u16],
}

impl<'a> FrameBuffer<'a> {
    /// Wraps a slice of at least [`BOX_SIZE`] RGB565 pixels.
    pub fn new(data: &'a mut [u16]) -> Self {
        assert!(data.len() >= BOX_SIZE, "framebuffer too small");
        Self { data }
    }

    /// Fills the whole frame with `color` (RGB565).
    pub fn clear(&mut self, color: u16) {
        self.data.fill(color);
    }

    /// Sets one pixel. Out-of-bounds coordinates are ignored.
    pub fn set_pixel(&mut self, x: u16, y: u16, color: u16) {
        if x < LCD_WIDTH && y < LCD_HEIGHT {
            self.data[y as usize * LCD_WIDTH as usize + x as usize] = color;
        }
    }

    /// Fills an axis-aligned rectangle, clipped to the panel bounds.
    pub fn fill_rect(&mut self, x: u16, y: u16, width: u16, height: u16, color: u16) {
        for row in y..y.saturating_add(height) {
            if row >= LCD_HEIGHT {
                break;
            }
            for col in x..x.saturating_add(width) {
                if col >= LCD_WIDTH {
                    break;
                }
                self.data[row as usize * LCD_WIDTH as usize + col as usize] = color;
            }
        }
    }

    /// Immutable view of the underlying pixels (e.g. for [`Axs15231b::flush`]).
    pub fn as_slice(&self) -> &[u16] {
        self.data
    }

    /// Mutable view of the underlying pixels.
    pub fn as_mut_slice(&mut self) -> &mut [u16] {
        self.data
    }
}
